esphome:
  name: esp-p1reader
  platform: esp32
  board: esp32dev
  includes:
    - p1reader.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp-p1reader"
    password: !secret fallback_password

captive_portal:

# Enable logging
logger:
  level: DEBUG
  baud_rate: 0 # disable logging over uart
  
# Enable Home Assistant API
api:
  password: !secret hass_api_password

ota:
  password: !secret ota_password

uart:
  id: uart_bus
    rx_pin:
      number: GPIO3
      inverted: true
  baud_rate: 115200
  
sensor:
- platform: custom

  lambda: |-
    auto meter_sensor = new P1Reader(id(uart_bus));
    App.register_component(meter_sensor);
    return {
      meter_sensor->pIn,
      meter_sensor->pOut,

      meter_sensor->u1,
      meter_sensor->u2,
      meter_sensor->u3,

      meter_sensor->i1,
      meter_sensor->i2,
      meter_sensor->i3,

      meter_sensor->eActiveIn,
      meter_sensor->eActiveInDay,
      meter_sensor->eActiveInNight,

      meter_sensor->eActiveOut,
      meter_sensor->eActiveOutDay,
      meter_sensor->eActiveOutNight,

      meter_sensor->p1In,
      meter_sensor->p2In,
      meter_sensor->p3In,

      meter_sensor->p1Out,
      meter_sensor->p2Out,
      meter_sensor->p3Out
    };
  
  sensors:
    - name: "Momentary Power Import"
      unit_of_measurement: kW
    accuracy_decimals: 3
      state_class: "measurement"
    device_class: "energy"
    - name: "Momentary Power Export"
      unit_of_measurement: kW
    accuracy_decimals: 3
      state_class: "measurement"
    device_class: "energy"
    
    - name: "Voltage Phase 1"
      unit_of_measurement: V
    accuracy_decimals: 3
      state_class: "measurement"
      device_class: "voltage"
    - name: "Voltage Phase 2"
      unit_of_measurement: V
    accuracy_decimals: 3
      state_class: "measurement"
      device_class: "voltage"
    - name: "Voltage Phase 3"
      unit_of_measurement: V
      accuracy_decimals: 3
      state_class: "measurement"
      device_class: "voltage"

    - name: "Current Phase 1"
      unit_of_measurement: A
      accuracy_decimals: 3
      state_class: "measurement"
      device_class: "current"
    - name: "Current Phase 2"
      unit_of_measurement: A
    accuracy_decimals: 3
    state_class: "measurement"
      device_class: "current"
    - name: "Current Phase 3"
      unit_of_measurement: A
    accuracy_decimals: 3
    state_class: "measurement"
      device_class: "current"

    - name: "Cumulative Active Energy Import"
      unit_of_measurement: kWh
      accuracy_decimals: 3
      state_class: "total_increasing"
      device_class: "energy"
    - name: "Cumulative Active Energy Import Day"
      unit_of_measurement: kWh
      accuracy_decimals: 3
      state_class: "total_increasing"
      device_class: "energy"
    - name: "Cumulative Active Energy Import Night"
      unit_of_measurement: kWh
      accuracy_decimals: 3
      state_class: "total_increasing"
      device_class: "energy"

    - name: "Cumulative Active Energy Export"
      unit_of_measurement: kWh
      accuracy_decimals: 3
      state_class: "total_increasing"
      device_class: "energy"
    - name: "Cumulative Active Energy Export Day"
      unit_of_measurement: kWh
    accuracy_decimals: 3
      state_class: "total_increasing"
      device_class: "energy"
    - name: "Cumulative Active Energy Export Night"
      unit_of_measurement: kWh
    accuracy_decimals: 3
      state_class: "total_increasing"
      device_class: "energy"

    - name: "Momentary Active Power Import Phase 1"
    unit_of_measurement: kW
    accuracy_decimals: 3
    state_class: "measurement"
    device_class: "power"
    - name: "Momentary Active Power Import Phase 2"
    unit_of_measurement: kW
    accuracy_decimals: 3
    state_class: "measurement"
    device_class: "power"
    - name: "Momentary Active Power Import Phase 3"
    unit_of_measurement: kW
    accuracy_decimals: 3
    state_class: "measurement"
    device_class: "power"

    - name: "Momentary Active Power Export Phase 1"
    unit_of_measurement: kW
    accuracy_decimals: 3
    state_class: "measurement"
    device_class: "power"
    - name: "Momentary Active Power Export Phase 2"
    unit_of_measurement: kW
    accuracy_decimals: 3
    state_class: "measurement"
    device_class: "power"
    - name: "Momentary Active Power Export Phase 3"
    unit_of_measurement: kW
    accuracy_decimals: 3
    state_class: "measurement"
    device_class: "power"
